<?php

namespace AppBundle\Entity\Cookie;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CookieRepository extends \Doctrine\ORM\EntityRepository
{
    function findCookies($cookieValue, $eleveId){
        $query = $this->createQueryBuilder('c')
        ->select('c')
            ->leftJoin('c.eleve','t')
            ->where('t.id != :eleveId')
            ->setParameter('eleveId',$eleveId)
            ->andWhere('c.cookie = :cookie')
            ->setParameter('cookie',$cookieValue)
            ->getQuery()->getResult();
        return $query;


    }
}
