<?php

namespace AppBundle\Entity\Cookie;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastMessages(){
        $startDate = time();
        $interval = date('Y-m-d H:i:s', strtotime('-120 second', $startDate));
        $query = $this->createQueryBuilder('m');
        $query = $query->select('m.content')
            ->addSelect('m.createdAt as date')
            ->leftJoin('m.eleve','t')
            ->addSelect('t.username as username')
            ->addSelect('t.slug as slug')
            ->addSelect('t.id as id')
            ->orderBy('m.createdAt','DESC')
            ->where('m.createdAt >= :date')
            ->setParameter('date',$interval);
        return $query->getQuery()->getResult();
        ;

    }
}
