<?php

namespace AppBundle\Entity\Cookie;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubmittedCookieRepository extends \Doctrine\ORM\EntityRepository
{
    public function countMySubmittedCookies($eleveId){
        return $this->createQueryBuilder('c')
        ->select('count(c) as nb')
            ->leftJoin('c.eleve','t')
            ->where('t.id = :eleveId')
            ->setParameter('eleveId',$eleveId)
            ->getQuery()->getSingleScalarResult();
    }
}
