<?php

namespace AppBundle\Entity;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscussionRepository extends \Doctrine\ORM\EntityRepository
{
    function findProjetDiscussions($id){
        $query = $this->createQueryBuilder('d');
        return $query
            ->select('d')
            ->leftJoin('d.projet','t')
            ->where("t.id = :id")
            ->setParameter('id',$id)
            ->leftJoin('d.sender', 's')
            ->addSelect('s')
            ->orderBy('d.createdAt','DESC')
            ->getQuery()->getResult();
    }
}
