<?php

namespace AppBundle\Entity;

/**
 * EleveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EleveRepository extends \Doctrine\ORM\EntityRepository
{
    function findAllEleves($filter, $filterValue, $order){

        $query = $this->createQueryBuilder('t');
        $query = $query
            ->select('t')
            ->leftJoin('t.participations', 'p')
            ->addSelect('p') ;

        if (($filter!="all")and($filter!="")and($filterValue!="")){
            if ($filter=="eleve"){
                $query=$query->where('upper(t.username) like :name')
                    ->setParameter('name','%'.strtoupper($filterValue).'%');
            }
            if ($filter=="organization"){
                $query=$query->where('upper(t.organisation) like :organization')
                    ->setParameter('organization','%'.strtoupper($filterValue).'%');
            }
            if ($filter=="country"){
                $query=$query->where('upper(t.country) like :country')
                    ->setParameter('country','%'.strtoupper($filterValue).'%');
            }
   // if ($filter=="country"){
     //           $query=$query->where('upper(t.country) like :country')
     //               ->setParameter('country','%'.strtoupper($filterValue).'%');
          //  }
        }
        if (($order=="")||($order=="eleve")){
            $query=$query->orderBy('t.username','ASC');
        }elseif ($order=="country"){
            $query=$query->orderBy('t.country','ASC');
        }
           return $query->andWhere('NOT (t.roles LIKE :roles)')->setParameter('roles', '%ROLE_ADMIN%')->andWhere('t.enabled = :v')->setParameter('v',true)
           
               ->getQuery()->getResult();
    }



    function findEleveBySlug($slug){
        $query = $this->createQueryBuilder('t');
        return $query
            ->select('t')
            ->leftJoin('t.participations', 'p')
            ->addSelect('p')
            ->leftJoin('p.promo','c')
            ->addSelect('c')
            ->where('t.slug like :slug')->setParameter('slug',$slug)
           
            ->getQuery()->getSingleResult();
    }


}