<?php

namespace AppBundle\Entity;

/**
 * Projet
 Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{
    function findAllWithStat($id){
//        $query = $this->createResultSetMappingBuilder('t')
//            ->addScalarResult('count(t)', 'c');

        $query = $this->createQueryBuilder('t');

        return $query
            ->select('t')
            ->where("t.promo = $id")
//            ->where($query->expr()->isNotNull('s.response'))
//           ->where('t.id = 10')
           //->leftJoin('t.submissions', 's')
           // ->addSelect('s')
           /// ->leftJoin('t.responses','r') 
            ///->addSelect('r')
//            ->groupBy('t')
            ->orderBy('t.createdAt','DESC')
            ->getQuery()->getResult();
    }

    public function findSuccessRateForProjetsBypromo($promoId){
        $query = $this->createQueryBuilder('t');
        $query = $query->select('t')
            ->where('t.promo = :promoId')
            ->setParameter('promoId',$promoId)
           // ->leftJoin('t.submissions','s')
           // ->addSelect('s')
            ->leftJoin('t.responses','r')
            ->andWhere('count(r.id)>0')->groupBy('t.id')
        ;
        return $query->getQuery()->getResult();
    }
}
