<?php

namespace AppBundle\Entity;

/**
 * PromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoRepository extends \Doctrine\ORM\EntityRepository
{
    function findAllPromos($filter, $filterValue, $order){

        $query = $this->createQueryBuilder('t');
        $query = $query
            ->select('t');
        if (($filter!="all")and($filter!="")and($filterValue!="")){
            if ($filter=="name"){
                $query=$query->where('upper(t.name) like :name')
                    ->setParameter('name','%'.strtoupper($filterValue).'%');
            }
        }
        if (($order=="")||($order=="name")){
            $query=$query->orderBy('t.name','ASC');
        }elseif ($order=="createdAt"){
            $query=$query->orderBy('t.createdAt','ASC');
        }elseif ($order=="endAt"){
            $query=$query->orderBy('t.endAt','ASC');
        }
        return $query ->getQuery()->getResult();
    }

    function findNextPromo(){
        $date = new \DateTime('now');
        $query = $this->createQueryBuilder('t');
        $query = $query
            ->select('t')->where('t.startAt > :now')
        ->setParameter('now',$date->format('Y-m-d h:i:s'))->orderBy('t.startAt','ASC')->setMaxResults(1);
        return $query ->getQuery()->getResult();
    }

    function findCurrentPromos(){
        $date = new \DateTime('now');
        $query = $this->createQueryBuilder('t');
        $query = $query
            ->select('t')->where('((t.startAt <= :now) and (:now < t.endAt))')
            ->setParameter('now',$date->format('Y-m-d h:i:s'))->orderBy('t.startAt','ASC');
        return $query ->getQuery()->getResult();
    }
}
